name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout the branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'
      - name: check for outdated dependencies
        run: |
          clojure -M:outdated | tee outdated.txt
          if [ $(grep -c ':mvn/version' outdated.txt) -gt 0 ]; then exit 1; fi
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTDATED_DEPS: $(cat outdated.txt)
        if: failure()
