name: Update dependencies
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'
      - name: check for outdated dependencies
        id: deps
        run: |
          echo 'Scheduled outdated dependency check:' >> outdated.md
          echo '```clojure' >> outdated.md
          clojure -M:outdated >> outdated.md
          echo '```' >> outdated.md
          if [ $(grep -c ':mvn/version' outdated.md) -gt 0 ]; then exit 1; fi
      - if: ${{ steps.deps.outputs.data == 1 }}
        name: Badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: dependencies
          LABEL: 'dependencies'
          STATUS: "out of date"
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.deps.outputs.data == 0 }}
        name: Badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: dependencies
          LABEL: 'dependencies'
          STATUS: "up to date"
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update stale dependencies
        run: |
          clojure -M:outdated --write
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updating stale dependencies
          title: Update stale dependencies
          body: Updating dependencies to the latest stable versions
          branch: update-dependencies
          base: master
