name: Update dependencies
on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update stale dependencies
        run: |
          clojure -M:outdated --write
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Updating stale dependencies
          title: Update Changelog
          body: Updating dependencies to the latest stable versions
          branch: update-dependencies
          base: master
